language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION dep1 dep2 ...
  - conda activate test-environment
  - python -m pip install .
script:
  - python test_read_csv.py
  - python test_average_data.py
  - python test_estimate_state_data.py
  - python test_estimate_state_data_regression.py
  - python test_decompose_data.py
  - python test_extract_in_crossroad_or_except_there.py
  - python test_learn_api.py
